// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7829I7H0ejAtHzc2Zg36NOD7-UWSOYxM',
    appId: '1:426623383168:web:a3ef7adf4da859a48a9865',
    messagingSenderId: '426623383168',
    projectId: 'event-management-app-80c64',
    authDomain: 'event-management-app-80c64.firebaseapp.com',
    storageBucket: 'event-management-app-80c64.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0qLgq-jUiE5qXLhOn8WQadViuRUP_cWo',
    appId: '1:426623383168:android:5d56f87cd89657328a9865',
    messagingSenderId: '426623383168',
    projectId: 'event-management-app-80c64',
    storageBucket: 'event-management-app-80c64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMpCifwb_y4hfl6yW_iABd-5PY3MqdfTU',
    appId: '1:426623383168:ios:9900ffb70e53d5cb8a9865',
    messagingSenderId: '426623383168',
    projectId: 'event-management-app-80c64',
    storageBucket: 'event-management-app-80c64.firebasestorage.app',
    iosBundleId: 'com.webwork.eventManagementApp',
  );
}
